import { HazardMarker, Shelter, FieldResponder, WorkOrder, CvPresetImage, WeatherData, Announcement } from './types';

export const INITIAL_HAZARD_MARKERS: HazardMarker[] = [
  // Chennai Markers (Primary Example Location)
  {
    id: 'c-1',
    name: 'Velachery Lowland (Lake Road)',
    locationId: 'chennai',
    risk: 86,
    status: 'danger',
    details: 'Heavy inundation risk. Velachery lake canal breach detected. Deep standing water rising.',
    population: 1400,
    lat: 12.9762,
    lng: 80.2181,
    radius: 1200, // 1.2 km radius
    x: 35, y: 60,
  },
  {
    id: 'c-2',
    name: 'Madipakkam Sector 3',
    locationId: 'chennai',
    risk: 74,
    status: 'warning',
    details: 'Severe storm drain overflow. Minor street flooding. Secondary drain water backed up.',
    population: 920,
    lat: 12.9509,
    lng: 80.2009,
    radius: 800, // 800 meters
    x: 52, y: 50,
  },
  {
    id: 'c-3',
    name: 'Perumbakkam Marshlands',
    locationId: 'chennai',
    risk: 92,
    status: 'danger',
    details: 'Saturated wetland runoff. Basements waterlogged in high-rise tenements. Power grids isolated.',
    population: 1800,
    lat: 12.9153,
    lng: 80.2042,
    radius: 1500, // 1.5 km radius
    x: 42, y: 75,
  },
  {
    id: 'c-s1',
    name: 'GCC Community Hall Adyar (Safe Haven)',
    locationId: 'chennai',
    risk: 2,
    status: 'safe',
    details: 'Designated GCC corporation shelter camp. Concrete halls, dry kitchen reserves, emergency medical unit.',
    population: 0,
    lat: 13.0067,
    lng: 80.2506,
    x: 22, y: 25,
  },
  {
    id: 'c-s2',
    name: 'Chennai Corp School Camp Velachery',
    locationId: 'chennai',
    risk: 4,
    status: 'safe',
    details: 'Protected municipal building. Clean water reservoir, emergency power backup, SDRF post.',
    population: 0,
    lat: 12.9802,
    lng: 80.2225,
    x: 65, y: 22,
  },
  {
    id: 'c-s3',
    name: 'IIT Madras Campus Shelter',
    locationId: 'chennai',
    risk: 2,
    status: 'safe',
    details: 'Elevated campus bedrock sector. Medical aid station and community food kitchen operational.',
    population: 0,
    lat: 12.9916,
    lng: 80.2336,
    x: 40, y: 30,
  },
  {
    id: 'c-s4',
    name: 'Tambaram Corporation School Camp',
    locationId: 'chennai',
    risk: 1,
    status: 'safe',
    details: 'GCC Safe Haven block. Emergency rations, dry kitchen, medical post for South Chennai.',
    population: 0,
    lat: 12.9229,
    lng: 80.1275,
    x: 10, y: 88,
  },
  {
    id: 'c-s5',
    name: 'Ambattur Industrial Estate Camp',
    locationId: 'chennai',
    risk: 2,
    status: 'safe',
    details: 'Reinforced logistics campus. Industrial capacity beds, reserve generators, active NGO hub.',
    population: 0,
    lat: 13.0900,
    lng: 80.1600,
    x: 8, y: 12,
  },
  {
    id: 'c-s6',
    name: 'Sholinganallur GCC Relief Center',
    locationId: 'chennai',
    risk: 1,
    status: 'safe',
    details: 'Coastal high-ground refuge camp. GCC designated concrete hall, drinking water storage.',
    population: 0,
    lat: 12.9010,
    lng: 80.2270,
    x: 45, y: 82,
  },
  {
    id: 'c-s7',
    name: 'Kanchipuram District Resettlement Haven',
    locationId: 'chennai',
    risk: 0,
    status: 'safe',
    details: 'Major regional emergency sanctuary. Permanent brick structure, medical dispensary.',
    population: 0,
    lat: 12.8342,
    lng: 79.7036,
    x: 5, y: 95,
  },
  {
    id: 'c-t-cbt',
    name: 'Coimbatore Hills Landslide Zone',
    locationId: 'chennai',
    risk: 68,
    status: 'warning',
    details: 'Slope saturation in Nilgiri foothill paths. Precautionary speed limits active on ghat roads.',
    population: 340,
    lat: 10.9780,
    lng: 76.8920,
    radius: 1200,
  },
  {
    id: 'c-s-cbt',
    name: 'Coimbatore Govt College Camp (Safe Haven)',
    locationId: 'chennai',
    risk: 2,
    status: 'safe',
    details: 'Safe inland sector relief base. Fully equipped medical bay, volunteer kitchen operational.',
    population: 0,
    lat: 11.0180,
    lng: 76.9558,
  },
  {
    id: 'c-t-mdu',
    name: 'Madurai Vaigai Basin Flood Area',
    locationId: 'chennai',
    risk: 72,
    status: 'warning',
    details: 'Vaigai Dam excess discharge drainage warning. Low-lying riverbeds waterlogged.',
    population: 580,
    lat: 9.9190,
    lng: 78.1190,
    radius: 1000,
  },
  {
    id: 'c-s-mdu',
    name: 'Madurai Corporation Relief Center',
    locationId: 'chennai',
    risk: 1,
    status: 'safe',
    details: 'High elevation public school camp. Dry food rations, safe drinking water tanks.',
    population: 0,
    lat: 9.9252,
    lng: 78.1312,
  },
  {
    id: 'c-t-try',
    name: 'Tiruchirappalli Kaveri Floodway',
    locationId: 'chennai',
    risk: 65,
    status: 'warning',
    details: 'Kaveri river flow height monitored. Lowland fields and delta channels showing overflow.',
    population: 430,
    lat: 10.8300,
    lng: 78.6900,
    radius: 1500,
  },
  {
    id: 'c-s-try',
    name: 'Trichy Central Railway Colony Camp',
    locationId: 'chennai',
    risk: 1,
    status: 'safe',
    details: 'Protected railway community sector. Safe shelter buildings, standby power grid.',
    population: 0,
    lat: 10.8050,
    lng: 78.6856,
  },
  {
    id: 'c-t-slm',
    name: 'Salem Yercaud Ghat Rockfall Risk',
    locationId: 'chennai',
    risk: 55,
    status: 'warning',
    details: 'Minor stone slides reported on Yercaud hairpin curves. Emergency crew on standby.',
    population: 190,
    lat: 11.7750,
    lng: 78.2090,
    radius: 1100,
  },
  {
    id: 'c-s-slm',
    name: 'Salem Municipal Stadium Relief Camp',
    locationId: 'chennai',
    risk: 3,
    status: 'safe',
    details: 'High-capacity indoor stadium haven. Basic healthcare camp, sanitation facilities.',
    population: 0,
    lat: 11.6643,
    lng: 78.1460,
  },
  {
    id: 'c-t-ten',
    name: 'Tirunelveli Thamirabarani Basin Flood',
    locationId: 'chennai',
    risk: 70,
    status: 'warning',
    details: 'Thamirabarani river discharge warning. Lowland residential margins waterlogged.',
    population: 410,
    lat: 8.7284,
    lng: 77.6891,
    radius: 1200,
  },
  {
    id: 'c-s-ten',
    name: 'Tirunelveli High School Relief Camp',
    locationId: 'chennai',
    risk: 2,
    status: 'safe',
    details: 'Elevated school building shelter. Food packets distribution post, medical unit.',
    population: 0,
    lat: 8.7139,
    lng: 77.7567,
  },
  {
    id: 'c-t-kk',
    name: 'Kanyakumari Coast Tide Surge',
    locationId: 'chennai',
    risk: 60,
    status: 'warning',
    details: 'High wave warning along shoreline. Fishing operations suspended, coast guard patrols active.',
    population: 260,
    lat: 8.0883,
    lng: 77.5385,
    radius: 1300,
  },
  {
    id: 'c-s-kk',
    name: 'Nagercoil Govt Arts College Camp',
    locationId: 'chennai',
    risk: 1,
    status: 'safe',
    details: 'Inland college campus haven. Concrete structures, backup water, emergency post.',
    population: 0,
    lat: 8.1883,
    lng: 77.4108,
  },
  {
    id: 'c-t-vel',
    name: 'Vellore Palar River Margin Overflow',
    locationId: 'chennai',
    risk: 52,
    status: 'warning',
    details: 'Precautionary watch on Palar river sand bed runoff. Sluice gates regulated.',
    population: 180,
    lat: 12.9230,
    lng: 79.1350,
    radius: 900,
  },
  {
    id: 'c-s-vel',
    name: 'Vellore Institute Shelter Enclave',
    locationId: 'chennai',
    risk: 1,
    status: 'safe',
    details: 'Reinforced bedrock campus halls. High resource capacity, dry rations depot.',
    population: 0,
    lat: 12.9692,
    lng: 79.1559,
  },
  {
    id: 'c-t-cud',
    name: 'Cuddalore Coastal Storm Surge',
    locationId: 'chennai',
    risk: 90,
    status: 'danger',
    details: 'Cyclonic storm surge inundation alert. Coastline villages relocated. Extreme rain forecast.',
    population: 1650,
    lat: 11.7480,
    lng: 79.7710,
    radius: 2000,
  },
  {
    id: 'c-s-cud',
    name: 'Cuddalore Port Relief Complex',
    locationId: 'chennai',
    risk: 2,
    status: 'safe',
    details: 'High bedrock concrete complex. Backup generators, medical station, kitchen.',
    population: 0,
    lat: 11.7580,
    lng: 79.7490,
  },
  {
    id: 'c-t-tj',
    name: 'Thanjavur Delta Inundation Sector',
    locationId: 'chennai',
    risk: 58,
    status: 'warning',
    details: 'Lowland paddy crop sectors waterlogged. Drain blockages cleared on Cauvery branches.',
    population: 290,
    lat: 10.7870,
    lng: 79.1378,
    radius: 1400,
  },
  {
    id: 'c-s-tj',
    name: 'Thanjavur Palace Ground Camp',
    locationId: 'chennai',
    risk: 1,
    status: 'safe',
    details: 'Spacious palace hall shelter. Rations storage, SDRF coordinate unit on site.',
    population: 0,
    lat: 10.7912,
    lng: 79.1310,
  },
  {
    id: 'c-t-tut',
    name: 'Thoothukudi Port Lowland Inundation',
    locationId: 'chennai',
    risk: 84,
    status: 'danger',
    details: 'High tide seawater intrusion in urban port lowlands. Storm pumps operational.',
    population: 870,
    lat: 8.7642,
    lng: 78.1348,
    radius: 1800,
  },
  {
    id: 'c-s-tut',
    name: 'Tuticorin VOC College Shelter',
    locationId: 'chennai',
    risk: 1,
    status: 'safe',
    details: 'High bedrock academic campus. Basic relief bedding, public kitchen, medical post.',
    population: 0,
    lat: 8.7900,
    lng: 78.1200,
  },

  // Wayanad Markers
  {
    id: 'w-1',
    name: 'Mundakkai Hamlet',
    locationId: 'wayanad',
    risk: 82,
    status: 'danger',
    details: 'Heavy slope instability. Saturated soil. High risk of immediate debris flow.',
    population: 450,
    lat: 11.5755,
    lng: 76.0533,
    radius: 1400, // 1.4 km radius
    x: 35, y: 65,
  },
  {
    id: 'w-2',
    name: 'Chooralmala Town',
    locationId: 'wayanad',
    risk: 58,
    status: 'warning',
    details: 'River level rising rapidly. Moderate landslide hazard monitored near old bridge.',
    population: 320,
    lat: 11.5712,
    lng: 76.0621,
    radius: 900,
    x: 45, y: 50,
  },
  {
    id: 'w-3',
    name: 'Puthumala Slope Area',
    locationId: 'wayanad',
    risk: 65,
    status: 'warning',
    details: 'Runoff velocity increased. Structural cracks noted in three retaining walls.',
    population: 180,
    lat: 11.5824,
    lng: 76.0795,
    radius: 1100,
    x: 60, y: 70,
  },
  {
    id: 'w-s1',
    name: 'GHSS Meppadi Relief Camp (Shelter Alpha)',
    locationId: 'wayanad',
    risk: 8,
    status: 'safe',
    details: 'Primary government shelter. Low slope angle, reinforced concrete structure, medical aid center.',
    population: 0,
    lat: 11.5601,
    lng: 76.0824,
    x: 20, y: 35,
  },
  {
    id: 'w-s2',
    name: 'Kalpetta Town Hall Relief Camp',
    locationId: 'wayanad',
    risk: 4,
    status: 'safe',
    details: 'District administration-run safe camp. Large carrying capacity, high food and kit reserves.',
    population: 0,
    lat: 11.6087,
    lng: 76.0830,
    x: 15, y: 15,
  },
  {
    id: 'w-s3',
    name: 'Vythiri Government High School',
    locationId: 'wayanad',
    risk: 3,
    status: 'safe',
    details: 'Municipal emergency camp. Free public kitchen, drinking water lines, medical post.',
    population: 0,
    lat: 11.5518,
    lng: 76.0425,
    x: 30, y: 40,
  },
  {
    id: 'w-s4',
    name: 'Mananthavady St. Patricks School Camp',
    locationId: 'wayanad',
    risk: 2,
    status: 'safe',
    details: 'Safe elevation, stable bedrock base. Kitchen reserves, large hall capacity.',
    population: 0,
    lat: 11.8020,
    lng: 76.0020,
    x: 10, y: 8,
  },
  {
    id: 'w-s5',
    name: 'Sulthan Bathery Municipal Camp',
    locationId: 'wayanad',
    risk: 1,
    status: 'safe',
    details: 'East Wayanad safety base camp. Equipped with municipal communications and logistics.',
    population: 0,
    lat: 11.6660,
    lng: 76.2560,
    x: 88, y: 22,
  },
  {
    id: 'w-s6',
    name: 'Meppadi GHSS Camp Beta',
    locationId: 'wayanad',
    risk: 3,
    status: 'safe',
    details: 'Concrete structure relief block. Backup water reservoirs and medical cabinets.',
    population: 0,
    lat: 11.5650,
    lng: 76.0880,
    x: 42, y: 55,
  },
  {
    id: 'w-t-tvm',
    name: 'Thiruvananthapuram Neyyar Canal Overflow',
    locationId: 'wayanad',
    risk: 74,
    status: 'warning',
    details: 'Canal spillway margin overflows. Water pumping active in low-lying city wards.',
    population: 620,
    lat: 8.5241,
    lng: 76.9366,
    radius: 1200,
  },
  {
    id: 'w-s-tvm',
    name: 'Trivandrum Central Stadium Relief Camp',
    locationId: 'wayanad',
    risk: 1,
    status: 'safe',
    details: 'District administration shelter hub. High reserves of rations and water.',
    population: 0,
    lat: 8.4890,
    lng: 76.9490,
  },
  {
    id: 'w-t-koc',
    name: 'Kochi Metro Tidal Inundation',
    locationId: 'wayanad',
    risk: 88,
    status: 'danger',
    details: 'High tide seawater intrusion and storm drain backing. Backwaters rising.',
    population: 1100,
    lat: 9.9816,
    lng: 76.2996,
    radius: 1600,
  },
  {
    id: 'w-s-koc',
    name: 'Kochi Naval Base Relief Camp',
    locationId: 'wayanad',
    risk: 2,
    status: 'safe',
    details: 'Protected military enclave. Concrete facilities, high logistics capability.',
    population: 0,
    lat: 9.9490,
    lng: 76.2730,
  },
  {
    id: 'w-t-clt',
    name: 'Kozhikode Mavoor Road Waterlogging',
    locationId: 'wayanad',
    risk: 62,
    status: 'warning',
    details: 'Standing runoff water on urban connector corridors. Traffic detours active.',
    population: 420,
    lat: 11.2588,
    lng: 75.7804,
    radius: 1000,
  },
  {
    id: 'w-s-clt',
    name: 'Kozhikode Govt Malabar College Camp',
    locationId: 'wayanad',
    risk: 1,
    status: 'safe',
    details: 'Municipal college camp. Safe halls, temporary public kitchen, medical post.',
    population: 0,
    lat: 11.2720,
    lng: 75.7950,
  },
  {
    id: 'w-t-tsr',
    name: 'Thrissur Kole Wetland Runoff Flood',
    locationId: 'wayanad',
    risk: 58,
    status: 'warning',
    details: 'Kole wetland saturated levels monitored. Precautionary dikes reinforced.',
    population: 280,
    lat: 10.5276,
    lng: 76.2144,
    radius: 1200,
  },
  {
    id: 'w-s-tsr',
    name: 'Thrissur Town Hall Camp',
    locationId: 'wayanad',
    risk: 1,
    status: 'safe',
    details: 'Secure bedrock town hall. Public shelter, basic health clinic, water reserves.',
    population: 0,
    lat: 10.5280,
    lng: 76.2180,
  },
  {
    id: 'w-t-knr',
    name: 'Kannur Iritty River Rise Alert',
    locationId: 'wayanad',
    risk: 64,
    status: 'warning',
    details: 'River level rising near Iritty ghat sector. Shoreline warnings dispatched.',
    population: 310,
    lat: 11.9790,
    lng: 75.6700,
    radius: 1300,
  },
  {
    id: 'w-s-knr',
    name: 'Kannur Fort Relief Camp',
    locationId: 'wayanad',
    risk: 2,
    status: 'safe',
    details: 'High stone wall fort sector. Protected from storm runoff, public kitchen active.',
    population: 0,
    lat: 11.8650,
    lng: 75.3620,
  },
  {
    id: 'w-t-klm',
    name: 'Kollam Ashtamudi Lake Overflow',
    locationId: 'wayanad',
    risk: 70,
    status: 'warning',
    details: 'Lake margin lowlands inundated. Precautionary evacuations active.',
    population: 390,
    lat: 8.8932,
    lng: 76.6141,
    radius: 1200,
  },
  {
    id: 'w-s-klm',
    name: 'Kollam Railway Colony Relief Center',
    locationId: 'wayanad',
    risk: 1,
    status: 'safe',
    details: 'Safe elevation colony halls. Dry food packets, clean water reserve.',
    population: 0,
    lat: 8.8870,
    lng: 76.5950,
  },
  {
    id: 'w-t-alp',
    name: 'Alappuzha Kuttanad Inundation Alert',
    locationId: 'wayanad',
    risk: 92,
    status: 'danger',
    details: 'Below sea-level polder walls breached. Severe water accumulation in Kuttanad basin.',
    population: 1950,
    lat: 9.4981,
    lng: 76.3328,
    radius: 2500,
  },
  {
    id: 'w-s-alp',
    name: 'Alappuzha SD College Camp',
    locationId: 'wayanad',
    risk: 2,
    status: 'safe',
    details: 'High bedrock college shelter. Safe from Kuttanad basin runoff. Rations operational.',
    population: 0,
    lat: 9.4750,
    lng: 76.3420,
  },
  {
    id: 'w-t-idk',
    name: 'Idukki Munnar Gap Road Debris Slide',
    locationId: 'wayanad',
    risk: 94,
    status: 'danger',
    details: 'Major mud/rock debris flow blocked Munnar road. High slope failure risk.',
    population: 480,
    lat: 10.0889,
    lng: 77.0600,
    radius: 1800,
  },
  {
    id: 'w-s-idk',
    name: 'Adimali Govt School Safe Camp',
    locationId: 'wayanad',
    risk: 1,
    status: 'safe',
    details: 'Low slope angle concrete school hall. Relief camp beds, safe drinking water.',
    population: 0,
    lat: 10.0120,
    lng: 76.9530,
  },
  {
    id: 'w-t-ktm',
    name: 'Kottayam Meenachil River Floodway',
    locationId: 'wayanad',
    risk: 68,
    status: 'warning',
    details: 'Meenachil river basin overflow in low-lying towns. Shoreline blockades active.',
    population: 430,
    lat: 9.5916,
    lng: 76.5221,
    radius: 1150,
  },
  {
    id: 'w-s-ktm',
    name: 'Kottayam CMS College Camp',
    locationId: 'wayanad',
    risk: 1,
    status: 'safe',
    details: 'Elevated academic campus haven. Dry food packs, safe water, first aid post.',
    population: 0,
    lat: 9.5930,
    lng: 76.5180,
  },
  {
    id: 'w-t-pkd',
    name: 'Palakkad Gap Wind Damage & Runoff',
    locationId: 'wayanad',
    risk: 52,
    status: 'warning',
    details: 'Heavy localized storm drainage overflows near Palakkad town limits.',
    population: 170,
    lat: 10.7867,
    lng: 76.6547,
    radius: 1000,
  },
  {
    id: 'w-s-pkd',
    name: 'Palakkad Victoria College Camp',
    locationId: 'wayanad',
    risk: 1,
    status: 'safe',
    details: 'Vast campus relief zone. Safe from local slope runoff, volunteer post operational.',
    population: 0,
    lat: 10.7890,
    lng: 76.6490,
  },

  // Joshimath Markers
  {
    id: 'j-1',
    name: 'Sunil Ward (Slope Creep)',
    locationId: 'joshimath',
    risk: 86,
    status: 'danger',
    details: 'Wide structural cracks (5cm+) in buildings. Ground subsidence active at 1.2cm/week.',
    population: 290,
    lat: 30.5618,
    lng: 79.5643,
    radius: 1000,
    x: 30, y: 55,
  },
  {
    id: 'j-2',
    name: 'Manohar Bagh Sector',
    locationId: 'joshimath',
    risk: 72,
    status: 'warning',
    details: 'Foundational shifting in residential zone. Ground water pressure rising.',
    population: 410,
    lat: 30.5538,
    lng: 79.5701,
    radius: 700,
    x: 48, y: 62,
  },
  {
    id: 'j-3',
    name: 'Marwari Lower Ward',
    locationId: 'joshimath',
    risk: 45,
    status: 'warning',
    details: 'Seepage from hydro-electric tunnel bypass monitored. Minor rockfall risk.',
    population: 150,
    lat: 30.5481,
    lng: 79.5621,
    radius: 800,
    x: 65, y: 45,
  },
  {
    id: 'j-s1',
    name: 'Gurudwara Joshimath Camp',
    locationId: 'joshimath',
    risk: 3,
    status: 'safe',
    details: 'Himalayan rescue base camp. Free lodging, community hot kitchen, satellite communications.',
    population: 0,
    lat: 30.5518,
    lng: 79.5635,
    x: 20, y: 20,
  },
  {
    id: 'j-s2',
    name: 'Helang Community Hall',
    locationId: 'joshimath',
    risk: 6,
    status: 'safe',
    details: 'Safe bedrock foundation. Equipped with municipal communications backup and first aid depot.',
    population: 0,
    lat: 30.5299,
    lng: 79.5481,
    x: 75, y: 25,
  },
  {
    id: 'j-s3',
    name: 'Pipalkoti Safety Dome',
    locationId: 'joshimath',
    risk: 2,
    status: 'safe',
    details: 'Stable valley floor relief zone. Integrated modular shelters and relief logistics center.',
    population: 0,
    lat: 30.4728,
    lng: 79.5031,
    x: 50, y: 10,
  },
  // User provided refuge centers
  {
    id: 'IN-AP-VIS-008',
    name: 'Ramayapatnam Cyclone Shelter',
    locationId: 'chennai',
    risk: 2,
    status: 'safe',
    details: 'Elevated ground floor, first-floor rescue rooms, separate toilets, community kitchen, reinforced steel cyclone doors',
    population: 0,
    lat: 17.6896,
    lng: 83.2185,
    x: 50, y: 50,
  },
  {
    id: 'IN-GJ-DWA-007',
    name: 'Dwarka Multipurpose Cyclone Shelter',
    locationId: 'chennai',
    risk: 2,
    status: 'safe',
    details: 'Community kitchen, stand-by medical team rooms, reinforced steel cyclone doors, multi-point locking systems',
    population: 0,
    lat: 22.2442,
    lng: 68.9685,
    x: 50, y: 50,
  },
  {
    id: 'IN-GJ-KUT-006',
    name: 'Maska Multipurpose Cyclone Shelter',
    locationId: 'chennai',
    risk: 2,
    status: 'safe',
    details: 'Community kitchen, stand-by medical team rooms, reinforced steel cyclone doors',
    population: 0,
    lat: 22.8425,
    lng: 69.3245,
    x: 50, y: 50,
  },
  {
    id: 'IN-JK-POO-011',
    name: 'Poonch Flood Rescue & Relief Center',
    locationId: 'chennai',
    risk: 2,
    status: 'safe',
    details: 'Emergency rescue equipment warehouse, temporary lodging rooms, indoor sanitation, first-aid unit',
    population: 0,
    lat: 33.6215,
    lng: 74.3412,
    x: 50, y: 50,
  },
  {
    id: 'IN-MH-PUN-012',
    name: 'Alandi Flood Relief Camp',
    locationId: 'chennai',
    risk: 2,
    status: 'safe',
    details: 'Large shared lodging hall, community kitchen, separate bathrooms, emergency medical desk',
    population: 0,
    lat: 18.6744,
    lng: 73.8998,
    x: 50, y: 50,
  },
  {
    id: 'IN-OD-BAL-004',
    name: 'Bahanaga Multipurpose Cyclone Shelter',
    locationId: 'chennai',
    risk: 2,
    status: 'safe',
    details: '4 big rooms & 2 smaller rooms (first floor), separate toilets, elevated ground floor',
    population: 0,
    lat: 21.3654,
    lng: 86.7325,
    x: 50, y: 50,
  },
  {
    id: 'IN-OD-BHA-005',
    name: 'Basudevpur Multipurpose Cyclone Shelter',
    locationId: 'chennai',
    risk: 2,
    status: 'safe',
    details: '4 big rooms & 2 smaller rooms (first floor), separate toilets, elevated ground floor',
    population: 0,
    lat: 21.1394,
    lng: 86.7215,
    x: 50, y: 50,
  },
  {
    id: 'IN-OD-GAN-003',
    name: 'Gopalpur Multipurpose Cyclone Shelter',
    locationId: 'chennai',
    risk: 2,
    status: 'safe',
    details: '4 big rooms & 2 smaller rooms (first floor), separate toilets, elevated ground floor',
    population: 0,
    lat: 19.2608,
    lng: 84.9083,
    x: 50, y: 50,
  },
  {
    id: 'IN-OD-PUR-002',
    name: 'Astaranga Multipurpose Cyclone Shelter',
    locationId: 'chennai',
    risk: 2,
    status: 'safe',
    details: '4 big rooms & 2 smaller rooms (first floor), separate toilets, elevated ground floor',
    population: 0,
    lat: 20.0264,
    lng: 86.2656,
    x: 50, y: 50,
  },
  {
    id: 'IN-OD-PUR-001',
    name: 'Satapada Multipurpose Cyclone Shelter',
    locationId: 'chennai',
    risk: 2,
    status: 'safe',
    details: '4 big rooms & 2 smaller rooms (first floor), separate toilets, elevated ground floor',
    population: 0,
    lat: 19.6702,
    lng: 85.6375,
    x: 50, y: 50,
  },
  {
    id: 'IN-TN-CHE-001',
    name: 'Velachery Relief & Rescue Center',
    locationId: 'chennai',
    risk: 2,
    status: 'safe',
    details: 'Shared lodging halls, primary healthcare clinic, water purification systems, backup power generators',
    population: 0,
    lat: 12.9802,
    lng: 80.2227,
    x: 50, y: 50,
  },
  {
    id: 'IN-TN-CUD-002',
    name: 'Cuddalore Multipurpose Cyclone Shelter',
    locationId: 'chennai',
    risk: 2,
    status: 'safe',
    details: 'Elevated ground floor, 4 large halls & 2 medical rooms, reinforced steel cyclone doors',
    population: 0,
    lat: 11.725,
    lng: 79.775,
    x: 50, y: 50,
  },
  {
    id: 'IN-TN-KAN-004',
    name: 'Kanyakumari Multi-Hazard Shelter',
    locationId: 'chennai',
    risk: 2,
    status: 'safe',
    details: 'Seawall-aligned windbreak structure, elevated ground floor, double-glazed laminated impact-resistant vision panels',
    population: 0,
    lat: 8.175,
    lng: 77.25,
    x: 50, y: 50,
  },
  {
    id: 'IN-TN-MAD-005',
    name: 'Madurai Regional Inland Relief Depot',
    locationId: 'chennai',
    risk: 2,
    status: 'safe',
    details: 'Inland flood relief depot with extensive dry ration and emergency medicine storage, large community shelter halls',
    population: 0,
    lat: 9.925,
    lng: 78.125,
    x: 50, y: 50,
  },
  {
    id: 'IN-TN-NAG-003',
    name: 'Nagapattinam Coastal Safe Zone',
    locationId: 'chennai',
    risk: 2,
    status: 'safe',
    details: 'Raised plinth above storm-surge level, wind-resistant RCC frame, high-importance factor structural layout',
    population: 0,
    lat: 10.375,
    lng: 79.85,
    x: 50, y: 50,
  },
  {
    id: 'IN-WB-S24-010',
    name: 'Sagar Island Multipurpose Cyclone Shelter',
    locationId: 'chennai',
    risk: 2,
    status: 'safe',
    details: 'Raised plinth / elevated ground floor, community kitchen, separate toilets, first-floor lodging',
    population: 0,
    lat: 21.6502,
    lng: 88.0833,
    x: 50, y: 50,
  }
];

export const INITIAL_SHELTERS: Shelter[] = [
  {
    id: 'IN-TN-CHE-001',
    name: 'Velachery Relief & Rescue Center',
    locationId: 'chennai',
    capacity: 2000,
    occupancy: Math.floor(2000 * 0.2),
    waterLevel: 100,
    rations: 100,
    medicalKits: 100,
    hospitalBeds: Math.floor(2000 * 0.1),
    personnelCount: 50,
    inventoryDetails: 'Historic safe zone added from SDRF dataset.',
    lat: 12.9802,
    lng: 80.2227
  },
  {
    id: 'IN-TN-CUD-002',
    name: 'Cuddalore Multipurpose Cyclone Shelter',
    locationId: 'chennai',
    capacity: 1200,
    occupancy: Math.floor(1200 * 0.2),
    waterLevel: 100,
    rations: 100,
    medicalKits: 100,
    hospitalBeds: Math.floor(1200 * 0.1),
    personnelCount: 50,
    inventoryDetails: 'Historic safe zone added from SDRF dataset.',
    lat: 11.725,
    lng: 79.775
  },
  {
    id: 'IN-TN-NAG-003',
    name: 'Nagapattinam Coastal Safe Zone',
    locationId: 'chennai',
    capacity: 1500,
    occupancy: Math.floor(1500 * 0.2),
    waterLevel: 100,
    rations: 100,
    medicalKits: 100,
    hospitalBeds: Math.floor(1500 * 0.1),
    personnelCount: 50,
    inventoryDetails: 'Historic safe zone added from SDRF dataset.',
    lat: 10.375,
    lng: 79.85
  },
  {
    id: 'IN-TN-KAN-004',
    name: 'Kanyakumari Multi-Hazard Shelter',
    locationId: 'chennai',
    capacity: 1000,
    occupancy: Math.floor(1000 * 0.2),
    waterLevel: 100,
    rations: 100,
    medicalKits: 100,
    hospitalBeds: Math.floor(1000 * 0.1),
    personnelCount: 50,
    inventoryDetails: 'Historic safe zone added from SDRF dataset.',
    lat: 8.175,
    lng: 77.25
  },
  {
    id: 'IN-TN-MAD-005',
    name: 'Madurai Regional Inland Relief Depot',
    locationId: 'chennai',
    capacity: 800,
    occupancy: Math.floor(800 * 0.2),
    waterLevel: 100,
    rations: 100,
    medicalKits: 100,
    hospitalBeds: Math.floor(800 * 0.1),
    personnelCount: 50,
    inventoryDetails: 'Historic safe zone added from SDRF dataset.',
    lat: 9.925,
    lng: 78.125
  },
  {
    id: 'IN-OD-PUR-001',
    name: 'Satapada Multipurpose Cyclone Shelter',
    locationId: 'chennai',
    capacity: 1000,
    occupancy: Math.floor(1000 * 0.2),
    waterLevel: 100,
    rations: 100,
    medicalKits: 100,
    hospitalBeds: Math.floor(1000 * 0.1),
    personnelCount: 50,
    inventoryDetails: 'Historic safe zone added from SDRF dataset.',
    lat: 19.6702,
    lng: 85.6375
  },
  {
    id: 'IN-OD-PUR-002',
    name: 'Astaranga Multipurpose Cyclone Shelter',
    locationId: 'chennai',
    capacity: 800,
    occupancy: Math.floor(800 * 0.2),
    waterLevel: 100,
    rations: 100,
    medicalKits: 100,
    hospitalBeds: Math.floor(800 * 0.1),
    personnelCount: 50,
    inventoryDetails: 'Historic safe zone added from SDRF dataset.',
    lat: 20.0264,
    lng: 86.2656
  },
  {
    id: 'IN-OD-GAN-003',
    name: 'Gopalpur Multipurpose Cyclone Shelter',
    locationId: 'chennai',
    capacity: 1500,
    occupancy: Math.floor(1500 * 0.2),
    waterLevel: 100,
    rations: 100,
    medicalKits: 100,
    hospitalBeds: Math.floor(1500 * 0.1),
    personnelCount: 50,
    inventoryDetails: 'Historic safe zone added from SDRF dataset.',
    lat: 19.2608,
    lng: 84.9083
  },
  {
    id: 'IN-OD-BAL-004',
    name: 'Bahanaga Multipurpose Cyclone Shelter',
    locationId: 'chennai',
    capacity: 1000,
    occupancy: Math.floor(1000 * 0.2),
    waterLevel: 100,
    rations: 100,
    medicalKits: 100,
    hospitalBeds: Math.floor(1000 * 0.1),
    personnelCount: 50,
    inventoryDetails: 'Historic safe zone added from SDRF dataset.',
    lat: 21.3654,
    lng: 86.7325
  },
  {
    id: 'IN-OD-BHA-005',
    name: 'Basudevpur Multipurpose Cyclone Shelter',
    locationId: 'chennai',
    capacity: 1200,
    occupancy: Math.floor(1200 * 0.2),
    waterLevel: 100,
    rations: 100,
    medicalKits: 100,
    hospitalBeds: Math.floor(1200 * 0.1),
    personnelCount: 50,
    inventoryDetails: 'Historic safe zone added from SDRF dataset.',
    lat: 21.1394,
    lng: 86.7215
  },
  {
    id: 'IN-GJ-KUT-006',
    name: 'Maska Multipurpose Cyclone Shelter',
    locationId: 'chennai',
    capacity: 1000,
    occupancy: Math.floor(1000 * 0.2),
    waterLevel: 100,
    rations: 100,
    medicalKits: 100,
    hospitalBeds: Math.floor(1000 * 0.1),
    personnelCount: 50,
    inventoryDetails: 'Historic safe zone added from SDRF dataset.',
    lat: 22.8425,
    lng: 69.3245
  },
  {
    id: 'IN-GJ-DWA-007',
    name: 'Dwarka Multipurpose Cyclone Shelter',
    locationId: 'chennai',
    capacity: 800,
    occupancy: Math.floor(800 * 0.2),
    waterLevel: 100,
    rations: 100,
    medicalKits: 100,
    hospitalBeds: Math.floor(800 * 0.1),
    personnelCount: 50,
    inventoryDetails: 'Historic safe zone added from SDRF dataset.',
    lat: 22.2442,
    lng: 68.9685
  },
  {
    id: 'IN-AP-VIS-008',
    name: 'Ramayapatnam Cyclone Shelter',
    locationId: 'chennai',
    capacity: 1500,
    occupancy: Math.floor(1500 * 0.2),
    waterLevel: 100,
    rations: 100,
    medicalKits: 100,
    hospitalBeds: Math.floor(1500 * 0.1),
    personnelCount: 50,
    inventoryDetails: 'Historic safe zone added from SDRF dataset.',
    lat: 17.6896,
    lng: 83.2185
  },
  {
    id: 'IN-TN-CHE-009',
    name: 'Velachery Relief & Rescue Center',
    locationId: 'chennai',
    capacity: 2000,
    occupancy: Math.floor(2000 * 0.2),
    waterLevel: 100,
    rations: 100,
    medicalKits: 100,
    hospitalBeds: Math.floor(2000 * 0.1),
    personnelCount: 50,
    inventoryDetails: 'Historic safe zone added from SDRF dataset.',
    lat: 12.9802,
    lng: 80.2227
  },
  {
    id: 'IN-WB-S24-010',
    name: 'Sagar Island Multipurpose Cyclone Shelter',
    locationId: 'chennai',
    capacity: 1200,
    occupancy: Math.floor(1200 * 0.2),
    waterLevel: 100,
    rations: 100,
    medicalKits: 100,
    hospitalBeds: Math.floor(1200 * 0.1),
    personnelCount: 50,
    inventoryDetails: 'Historic safe zone added from SDRF dataset.',
    lat: 21.6502,
    lng: 88.0833
  },
  {
    id: 'IN-JK-POO-011',
    name: 'Poonch Flood Rescue & Relief Center',
    locationId: 'chennai',
    capacity: 600,
    occupancy: Math.floor(600 * 0.2),
    waterLevel: 100,
    rations: 100,
    medicalKits: 100,
    hospitalBeds: Math.floor(600 * 0.1),
    personnelCount: 50,
    inventoryDetails: 'Historic safe zone added from SDRF dataset.',
    lat: 33.6215,
    lng: 74.3412
  },
  {
    id: 'IN-MH-PUN-012',
    name: 'Alandi Flood Relief Camp',
    locationId: 'chennai',
    capacity: 500,
    occupancy: Math.floor(500 * 0.2),
    waterLevel: 100,
    rations: 100,
    medicalKits: 100,
    hospitalBeds: Math.floor(500 * 0.1),
    personnelCount: 50,
    inventoryDetails: 'Historic safe zone added from SDRF dataset.',
    lat: 18.6744,
    lng: 73.8998
  },
  // Chennai Shelters
  {
    id: 'c-s1',
    name: 'GCC Community Hall Adyar (Safe Haven)',
    locationId: 'chennai',
    capacity: 800,
    occupancy: 240,
    waterLevel: 92,
    rations: 88,
    medicalKits: 90,
    lat: 13.0067,
    lng: 80.2506,
  },
  {
    id: 'c-s2',
    name: 'Chennai Corp School Camp Velachery',
    locationId: 'chennai',
    capacity: 500,
    occupancy: 150,
    waterLevel: 85,
    rations: 82,
    medicalKits: 80,
    lat: 12.9802,
    lng: 80.2225,
  },
  {
    id: 'c-s3',
    name: 'IIT Madras Campus Shelter',
    locationId: 'chennai',
    capacity: 600,
    occupancy: 120,
    waterLevel: 95,
    rations: 90,
    medicalKits: 85,
    lat: 12.9916,
    lng: 80.2336,
  },
  {
    id: 'c-s4',
    name: 'Tambaram Corporation School Camp',
    locationId: 'chennai',
    capacity: 600,
    occupancy: 0,
    waterLevel: 90,
    rations: 85,
    medicalKits: 80,
    lat: 12.9229,
    lng: 80.1275,
  },
  {
    id: 'c-s5',
    name: 'Ambattur Industrial Estate Camp',
    locationId: 'chennai',
    capacity: 700,
    occupancy: 0,
    waterLevel: 88,
    rations: 80,
    medicalKits: 85,
    lat: 13.0900,
    lng: 80.1600,
  },
  {
    id: 'c-s6',
    name: 'Sholinganallur GCC Relief Center',
    locationId: 'chennai',
    capacity: 550,
    occupancy: 0,
    waterLevel: 92,
    rations: 85,
    medicalKits: 80,
    lat: 12.9010,
    lng: 80.2270,
  },
  {
    id: 'c-s7',
    name: 'Kanchipuram District Resettlement Haven',
    locationId: 'chennai',
    capacity: 1200,
    occupancy: 0,
    waterLevel: 95,
    rations: 90,
    medicalKits: 95,
    lat: 12.8342,
    lng: 79.7036,
  },
  {
    id: 'c-s-cbt',
    name: 'Coimbatore Govt College Camp (Safe Haven)',
    locationId: 'chennai',
    capacity: 700,
    occupancy: 0,
    waterLevel: 90,
    rations: 85,
    medicalKits: 85,
    lat: 11.0180,
    lng: 76.9558,
  },
  {
    id: 'c-s-mdu',
    name: 'Madurai Corporation Relief Center',
    locationId: 'chennai',
    capacity: 500,
    occupancy: 0,
    waterLevel: 85,
    rations: 80,
    medicalKits: 80,
    lat: 9.9252,
    lng: 78.1312,
  },
  {
    id: 'c-s-try',
    name: 'Trichy Central Railway Colony Camp',
    locationId: 'chennai',
    capacity: 600,
    occupancy: 0,
    waterLevel: 88,
    rations: 82,
    medicalKits: 85,
    lat: 10.8050,
    lng: 78.6856,
  },
  {
    id: 'c-s-slm',
    name: 'Salem Municipal Stadium Relief Camp',
    locationId: 'chennai',
    capacity: 1000,
    occupancy: 0,
    waterLevel: 92,
    rations: 88,
    medicalKits: 90,
    lat: 11.6643,
    lng: 78.1460,
  },
  {
    id: 'c-s-ten',
    name: 'Tirunelveli High School Relief Camp',
    locationId: 'chennai',
    capacity: 500,
    occupancy: 0,
    waterLevel: 85,
    rations: 80,
    medicalKits: 82,
    lat: 8.7139,
    lng: 77.7567,
  },
  {
    id: 'c-s-kk',
    name: 'Nagercoil Govt Arts College Camp',
    locationId: 'chennai',
    capacity: 600,
    occupancy: 0,
    waterLevel: 90,
    rations: 85,
    medicalKits: 80,
    lat: 8.1883,
    lng: 77.4108,
  },
  {
    id: 'c-s-vel',
    name: 'Vellore Institute Shelter Enclave',
    locationId: 'chennai',
    capacity: 800,
    occupancy: 0,
    waterLevel: 95,
    rations: 90,
    medicalKits: 90,
    lat: 12.9692,
    lng: 79.1559,
  },
  {
    id: 'c-s-cud',
    name: 'Cuddalore Port Relief Complex',
    locationId: 'chennai',
    capacity: 900,
    occupancy: 0,
    waterLevel: 88,
    rations: 85,
    medicalKits: 88,
    lat: 11.7580,
    lng: 79.7490,
  },
  {
    id: 'c-s-tj',
    name: 'Thanjavur Palace Ground Camp',
    locationId: 'chennai',
    capacity: 500,
    occupancy: 0,
    waterLevel: 90,
    rations: 85,
    medicalKits: 80,
    lat: 10.7912,
    lng: 79.1310,
  },
  {
    id: 'c-s-tut',
    name: 'Tuticorin VOC College Shelter',
    locationId: 'chennai',
    capacity: 700,
    occupancy: 0,
    waterLevel: 85,
    rations: 80,
    medicalKits: 85,
    lat: 8.7900,
    lng: 78.1200,
  },
  // Wayanad Shelters
  {
    id: 'w-s1',
    name: 'GHSS Meppadi Relief Camp (Shelter Alpha)',
    locationId: 'wayanad',
    capacity: 500,
    occupancy: 150,
    waterLevel: 82,
    rations: 78,
    medicalKits: 85,
    lat: 11.5601,
    lng: 76.0824,
  },
  {
    id: 'w-s2',
    name: 'Kalpetta Town Hall Relief Camp',
    locationId: 'wayanad',
    capacity: 400,
    occupancy: 100,
    waterLevel: 90,
    rations: 92,
    medicalKits: 80,
    lat: 11.6087,
    lng: 76.0830,
  },
  {
    id: 'w-s3',
    name: 'Vythiri Government High School',
    locationId: 'wayanad',
    capacity: 300,
    occupancy: 45,
    waterLevel: 80,
    rations: 85,
    medicalKits: 75,
    lat: 11.5518,
    lng: 76.0425,
  },
  {
    id: 'w-s4',
    name: 'Mananthavady St. Patricks School Camp',
    locationId: 'wayanad',
    capacity: 450,
    occupancy: 0,
    waterLevel: 90,
    rations: 85,
    medicalKits: 80,
    lat: 11.8020,
    lng: 76.0020,
  },
  {
    id: 'w-s5',
    name: 'Sulthan Bathery Municipal Camp',
    locationId: 'wayanad',
    capacity: 500,
    occupancy: 0,
    waterLevel: 92,
    rations: 88,
    medicalKits: 85,
    lat: 11.6660,
    lng: 76.2560,
  },
  {
    id: 'w-s6',
    name: 'Meppadi GHSS Camp Beta',
    locationId: 'wayanad',
    capacity: 350,
    occupancy: 0,
    waterLevel: 85,
    rations: 80,
    medicalKits: 90,
    lat: 11.5650,
    lng: 76.0880,
  },
  {
    id: 'w-s-tvm',
    name: 'Trivandrum Central Stadium Relief Camp',
    locationId: 'wayanad',
    capacity: 900,
    occupancy: 0,
    waterLevel: 92,
    rations: 90,
    medicalKits: 92,
    lat: 8.4890,
    lng: 76.9490,
  },
  {
    id: 'w-s-koc',
    name: 'Kochi Naval Base Relief Camp',
    locationId: 'wayanad',
    capacity: 1000,
    occupancy: 0,
    waterLevel: 95,
    rations: 90,
    medicalKits: 95,
    lat: 9.9490,
    lng: 76.2730,
  },
  {
    id: 'w-s-clt',
    name: 'Kozhikode Govt Malabar College Camp',
    locationId: 'wayanad',
    capacity: 600,
    occupancy: 0,
    waterLevel: 88,
    rations: 85,
    medicalKits: 80,
    lat: 11.2720,
    lng: 75.7950,
  },
  {
    id: 'w-s-tsr',
    name: 'Thrissur Town Hall Camp',
    locationId: 'wayanad',
    capacity: 500,
    occupancy: 0,
    waterLevel: 90,
    rations: 85,
    medicalKits: 85,
    lat: 10.5280,
    lng: 76.2180,
  },
  {
    id: 'w-s-knr',
    name: 'Kannur Fort Relief Camp',
    locationId: 'wayanad',
    capacity: 700,
    occupancy: 0,
    waterLevel: 85,
    rations: 80,
    medicalKits: 80,
    lat: 11.8650,
    lng: 75.3620,
  },
  {
    id: 'w-s-klm',
    name: 'Kollam Railway Colony Relief Center',
    locationId: 'wayanad',
    capacity: 550,
    occupancy: 0,
    waterLevel: 90,
    rations: 85,
    medicalKits: 85,
    lat: 8.8870,
    lng: 76.5950,
  },
  {
    id: 'w-s-alp',
    name: 'Alappuzha SD College Camp',
    locationId: 'wayanad',
    capacity: 1000,
    occupancy: 0,
    waterLevel: 90,
    rations: 85,
    medicalKits: 88,
    lat: 9.4750,
    lng: 76.3420,
  },
  {
    id: 'w-s-idk',
    name: 'Adimali Govt School Safe Camp',
    locationId: 'wayanad',
    capacity: 400,
    occupancy: 0,
    waterLevel: 85,
    rations: 80,
    medicalKits: 80,
    lat: 10.0120,
    lng: 76.9530,
  },
  {
    id: 'w-s-ktm',
    name: 'Kottayam CMS College Camp',
    locationId: 'wayanad',
    capacity: 500,
    occupancy: 0,
    waterLevel: 90,
    rations: 85,
    medicalKits: 85,
    lat: 9.5930,
    lng: 76.5180,
  },
  {
    id: 'w-s-pkd',
    name: 'Palakkad Victoria College Camp',
    locationId: 'wayanad',
    capacity: 600,
    occupancy: 0,
    waterLevel: 92,
    rations: 88,
    medicalKits: 88,
    lat: 10.7890,
    lng: 76.6490,
  },
  // Joshimath Shelters
  {
    id: 'j-s1',
    name: 'Gurudwara Joshimath Camp',
    locationId: 'joshimath',
    capacity: 600,
    occupancy: 180,
    waterLevel: 95,
    rations: 88,
    medicalKits: 92,
    lat: 30.5518,
    lng: 79.5635,
  },
  {
    id: 'j-s2',
    name: 'Helang Community Hall',
    locationId: 'joshimath',
    capacity: 350,
    occupancy: 70,
    waterLevel: 80,
    rations: 85,
    medicalKits: 75,
    lat: 30.5299,
    lng: 79.5481,
  },
  {
    id: 'j-s3',
    name: 'Pipalkoti Safety Dome',
    locationId: 'joshimath',
    capacity: 450,
    occupancy: 80,
    waterLevel: 90,
    rations: 85,
    medicalKits: 80,
    lat: 30.4728,
    lng: 79.5031,
  },
];

export const INITIAL_RESPONDERS: FieldResponder[] = [
  {
    id: 'res-1',
    name: 'NDMA Rescue Unit-Alpha',
    type: 'Police',
    status: 'idle',
    location: 'District HQ Command Center',
    progress: 0,
    taskId: null,
  },
  {
    id: 'res-2',
    name: 'SDRF Fire & Hazard Unit-3',
    type: 'Fire',
    status: 'idle',
    location: 'Central Valley Station',
    progress: 0,
    taskId: null,
  },
  {
    id: 'res-3',
    name: 'Red Cross Medical Team Delta',
    type: 'Medical',
    status: 'idle',
    location: 'Regional Hospital Hub',
    progress: 0,
    taskId: null,
  },
  {
    id: 'res-4',
    name: 'SEWA Response Volunteers',
    type: 'NGO',
    status: 'idle',
    location: 'Civic Support Warehouse',
    progress: 0,
    taskId: null,
  },
];

export const INITIAL_WORK_ORDERS: WorkOrder[] = [
  {
    id: 'wo-100',
    title: 'Velachery storm drain clearance',
    description: 'Immediate clearance of stormwater conduits to drain excess runoff from Velachery main junction.',
    source: 'Simulator',
    locationId: 'chennai',
    locationName: 'Velachery Lowland (Lake Road)',
    priority: 'critical',
    status: 'pending',
    assignedResponderId: null,
    progress: 0,
  },
  {
    id: 'wo-101',
    title: 'Slope Retaining Wall reinforcement',
    description: 'Provide immediate support beams to the shifting retaining wall in Puthumala to avoid road blockages.',
    source: 'Simulator',
    locationId: 'wayanad',
    locationName: 'Puthumala Slope Area',
    priority: 'medium',
    status: 'pending',
    assignedResponderId: null,
    progress: 0,
  },
  {
    id: 'wo-102',
    title: 'Drainage blockage clearing',
    description: 'Clear structural drainage channels near Sunil Ward to reduce soil pore-water pressure and slow creep rate.',
    source: 'Simulator',
    locationId: 'joshimath',
    locationName: 'Sunil Ward (Slope Creep)',
    priority: 'critical',
    status: 'pending',
    assignedResponderId: null,
    progress: 0,
  },
];

export const CV_PRESET_IMAGES: CvPresetImage[] = [
  {
    id: 'cv-img-1',
    name: 'Mountain Road Pothole',
    url: '/road_pothole.jpg',
    hazardType: 'Road Surface Degradation / Deep Pothole',
    confidence: 94.2,
    locationTag: 'Mundakkai Access Rd (Wayanad)',
    boundingBoxes: [
      {
        x: 15,
        y: 52,
        w: 62,
        h: 38,
        label: 'Pothole (Severity: High)',
        confidence: 94.2,
      },
    ],
  },
  {
    id: 'cv-img-2',
    name: 'Tension Fissure Creep',
    url: '/road_crack.jpg',
    hazardType: 'Tension Crack / Subsidence Creep',
    confidence: 96.8,
    locationTag: 'Sunil Ward Sector-4 (Joshimath)',
    boundingBoxes: [
      {
        x: 3,
        y: 38,
        w: 92,
        h: 56,
        label: 'Fissure Gap (Subsidence Alert)',
        confidence: 96.8,
      },
    ],
  },
];

export const INITIAL_WEATHER: Record<string, WeatherData> = {
  chennai: {
    precipitation: 28.5,
    temperature: 28.0,
    humidity: 88,
    windSpeed: 32.0,
    imdAlertLevel: 'red',
  },
  wayanad: {
    precipitation: 14.5,
    temperature: 22.0,
    humidity: 92,
    windSpeed: 21.5,
    imdAlertLevel: 'orange',
  },
  joshimath: {
    precipitation: 0.0,
    temperature: 13.8,
    humidity: 58,
    windSpeed: 9.0,
    imdAlertLevel: 'yellow',
  },
};

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  // Chennai
  {
    id: 'ann-c-1',
    time: '08:00 AM',
    source: 'Tamil Nadu SDMA',
    message: 'RED ALERT: Extreme rain warnings issued for Chennai. Command centers deployed for stormwater extraction.',
  },
  {
    id: 'ann-c-2',
    time: '09:30 AM',
    source: 'Greater Chennai Corp',
    message: 'IIT Madras relief shelter camp active and provisioning dry rations. Helplines open at 1913.',
  },
  // Wayanad
  {
    id: 'ann-w-1',
    time: '10:45 AM',
    source: 'Kerala SDMA',
    message: 'Orange Alert issued for Vythiri, Mananthavady, and Sulthan Bathery taluks. Avoid travel near steep slopes.',
  },
  {
    id: 'ann-w-2',
    time: '02:30 PM',
    source: 'Wayanad District Collector',
    message: 'Relocation shelters Alpha and Beta are open. Rations and emergency responders are on standby.',
  },
  // Joshimath
  {
    id: 'ann-j-1',
    time: '09:15 AM',
    source: 'Uttarakhand SDMA',
    message: 'Continuous monitoring of tension cracks in Sunil Ward and Manohar Bagh active. Geologists deployed.',
  },
  {
    id: 'ann-j-2',
    time: '01:50 PM',
    source: 'Chamoli DM Office',
    message: 'Pipalkoti Safety Dome operational. Rescue helplines activated. Dial 1077 for emergency support.',
  },
];
