import { HazardMarker, Shelter, FieldResponder, WorkOrder, CvPresetImage, WeatherData, Announcement } from './types';

export const INITIAL_HAZARD_MARKERS: HazardMarker[] = [
  // Chennai Markers (Primary Example Location)
  {
    id: 'c-1',
    name: 'Velachery Lowland (Lake Road)',
    locationId: 'chennai',
    risk: 86,
    status: 'danger',
    details: 'Heavy inundation risk. Velachery lake canal breach detected. Deep standing water rising.',
    population: 1400,
    lat: 12.9762,
    lng: 80.2181,
    radius: 1200, // 1.2 km radius
    x: 35, y: 60,
  },
  {
    id: 'c-2',
    name: 'Madipakkam Sector 3',
    locationId: 'chennai',
    risk: 74,
    status: 'warning',
    details: 'Severe storm drain overflow. Minor street flooding. Secondary drain water backed up.',
    population: 920,
    lat: 12.9509,
    lng: 80.2009,
    radius: 800, // 800 meters
    x: 52, y: 50,
  },
  {
    id: 'c-3',
    name: 'Perumbakkam Marshlands',
    locationId: 'chennai',
    risk: 92,
    status: 'danger',
    details: 'Saturated wetland runoff. Basements waterlogged in high-rise tenements. Power grids isolated.',
    population: 1800,
    lat: 12.9153,
    lng: 80.2042,
    radius: 1500, // 1.5 km radius
    x: 42, y: 75,
  },
  {
    id: 'c-s1',
    name: 'GCC Community Hall Adyar (Safe Haven)',
    locationId: 'chennai',
    risk: 2,
    status: 'safe',
    details: 'Designated GCC corporation shelter camp. Concrete halls, dry kitchen reserves, emergency medical unit.',
    population: 0,
    lat: 13.0067,
    lng: 80.2506,
    x: 22, y: 25,
  },
  {
    id: 'c-s2',
    name: 'Chennai Corp School Camp Velachery',
    locationId: 'chennai',
    risk: 4,
    status: 'safe',
    details: 'Protected municipal building. Clean water reservoir, emergency power backup, SDRF post.',
    population: 0,
    lat: 12.9802,
    lng: 80.2225,
    x: 65, y: 22,
  },
  {
    id: 'c-s3',
    name: 'IIT Madras Campus Shelter',
    locationId: 'chennai',
    risk: 2,
    status: 'safe',
    details: 'Elevated campus bedrock sector. Medical aid station and community food kitchen operational.',
    population: 0,
    lat: 12.9916,
    lng: 80.2336,
    x: 40, y: 30,
  },

  // Wayanad Markers
  {
    id: 'w-1',
    name: 'Mundakkai Hamlet',
    locationId: 'wayanad',
    risk: 82,
    status: 'danger',
    details: 'Heavy slope instability. Saturated soil. High risk of immediate debris flow.',
    population: 450,
    lat: 11.5755,
    lng: 76.0533,
    radius: 1400, // 1.4 km radius
    x: 35, y: 65,
  },
  {
    id: 'w-2',
    name: 'Chooralmala Town',
    locationId: 'wayanad',
    risk: 58,
    status: 'warning',
    details: 'River level rising rapidly. Moderate landslide hazard monitored near old bridge.',
    population: 320,
    lat: 11.5712,
    lng: 76.0621,
    radius: 900,
    x: 45, y: 50,
  },
  {
    id: 'w-3',
    name: 'Puthumala Slope Area',
    locationId: 'wayanad',
    risk: 65,
    status: 'warning',
    details: 'Runoff velocity increased. Structural cracks noted in three retaining walls.',
    population: 180,
    lat: 11.5824,
    lng: 76.0795,
    radius: 1100,
    x: 60, y: 70,
  },
  {
    id: 'w-s1',
    name: 'GHSS Meppadi Relief Camp (Shelter Alpha)',
    locationId: 'wayanad',
    risk: 8,
    status: 'safe',
    details: 'Primary government shelter. Low slope angle, reinforced concrete structure, medical aid center.',
    population: 0,
    lat: 11.5601,
    lng: 76.0824,
    x: 20, y: 35,
  },
  {
    id: 'w-s2',
    name: 'Kalpetta Town Hall Relief Camp',
    locationId: 'wayanad',
    risk: 4,
    status: 'safe',
    details: 'District administration-run safe camp. Large carrying capacity, high food and kit reserves.',
    population: 0,
    lat: 11.6087,
    lng: 76.0830,
    x: 15, y: 15,
  },
  {
    id: 'w-s3',
    name: 'Vythiri Government High School',
    locationId: 'wayanad',
    risk: 3,
    status: 'safe',
    details: 'Municipal emergency camp. Free public kitchen, drinking water lines, medical post.',
    population: 0,
    lat: 11.5518,
    lng: 76.0425,
    x: 30, y: 40,
  },

  // Joshimath Markers
  {
    id: 'j-1',
    name: 'Sunil Ward (Slope Creep)',
    locationId: 'joshimath',
    risk: 86,
    status: 'danger',
    details: 'Wide structural cracks (5cm+) in buildings. Ground subsidence active at 1.2cm/week.',
    population: 290,
    lat: 30.5618,
    lng: 79.5643,
    radius: 1000,
    x: 30, y: 55,
  },
  {
    id: 'j-2',
    name: 'Manohar Bagh Sector',
    locationId: 'joshimath',
    risk: 72,
    status: 'warning',
    details: 'Foundational shifting in residential zone. Ground water pressure rising.',
    population: 410,
    lat: 30.5538,
    lng: 79.5701,
    radius: 700,
    x: 48, y: 62,
  },
  {
    id: 'j-3',
    name: 'Marwari Lower Ward',
    locationId: 'joshimath',
    risk: 45,
    status: 'warning',
    details: 'Seepage from hydro-electric tunnel bypass monitored. Minor rockfall risk.',
    population: 150,
    lat: 30.5481,
    lng: 79.5621,
    radius: 800,
    x: 65, y: 45,
  },
  {
    id: 'j-s1',
    name: 'Gurudwara Joshimath Camp',
    locationId: 'joshimath',
    risk: 3,
    status: 'safe',
    details: 'Himalayan rescue base camp. Free lodging, community hot kitchen, satellite communications.',
    population: 0,
    lat: 30.5518,
    lng: 79.5635,
    x: 20, y: 20,
  },
  {
    id: 'j-s2',
    name: 'Helang Community Hall',
    locationId: 'joshimath',
    risk: 6,
    status: 'safe',
    details: 'Safe bedrock foundation. Equipped with municipal communications backup and first aid depot.',
    population: 0,
    lat: 30.5299,
    lng: 79.5481,
    x: 75, y: 25,
  },
  {
    id: 'j-s3',
    name: 'Pipalkoti Safety Dome',
    locationId: 'joshimath',
    risk: 2,
    status: 'safe',
    details: 'Stable valley floor relief zone. Integrated modular shelters and relief logistics center.',
    population: 0,
    lat: 30.4728,
    lng: 79.5031,
    x: 50, y: 10,
  },
];

export const INITIAL_SHELTERS: Shelter[] = [
  // Chennai Shelters
  {
    id: 'c-s1',
    name: 'GCC Community Hall Adyar (Safe Haven)',
    locationId: 'chennai',
    capacity: 800,
    occupancy: 240,
    waterLevel: 92,
    rations: 88,
    medicalKits: 90,
    lat: 13.0067,
    lng: 80.2506,
  },
  {
    id: 'c-s2',
    name: 'Chennai Corp School Camp Velachery',
    locationId: 'chennai',
    capacity: 500,
    occupancy: 150,
    waterLevel: 85,
    rations: 82,
    medicalKits: 80,
    lat: 12.9802,
    lng: 80.2225,
  },
  {
    id: 'c-s3',
    name: 'IIT Madras Campus Shelter',
    locationId: 'chennai',
    capacity: 600,
    occupancy: 120,
    waterLevel: 95,
    rations: 90,
    medicalKits: 85,
    lat: 12.9916,
    lng: 80.2336,
  },
  // Wayanad Shelters
  {
    id: 'w-s1',
    name: 'GHSS Meppadi Relief Camp (Shelter Alpha)',
    locationId: 'wayanad',
    capacity: 500,
    occupancy: 150,
    waterLevel: 82,
    rations: 78,
    medicalKits: 85,
    lat: 11.5601,
    lng: 76.0824,
  },
  {
    id: 'w-s2',
    name: 'Kalpetta Town Hall Relief Camp',
    locationId: 'wayanad',
    capacity: 400,
    occupancy: 100,
    waterLevel: 90,
    rations: 92,
    medicalKits: 80,
    lat: 11.6087,
    lng: 76.0830,
  },
  {
    id: 'w-s3',
    name: 'Vythiri Government High School',
    locationId: 'wayanad',
    capacity: 300,
    occupancy: 45,
    waterLevel: 80,
    rations: 85,
    medicalKits: 75,
    lat: 11.5518,
    lng: 76.0425,
  },
  // Joshimath Shelters
  {
    id: 'j-s1',
    name: 'Gurudwara Joshimath Camp',
    locationId: 'joshimath',
    capacity: 600,
    occupancy: 180,
    waterLevel: 95,
    rations: 88,
    medicalKits: 92,
    lat: 30.5518,
    lng: 79.5635,
  },
  {
    id: 'j-s2',
    name: 'Helang Community Hall',
    locationId: 'joshimath',
    capacity: 350,
    occupancy: 70,
    waterLevel: 80,
    rations: 85,
    medicalKits: 75,
    lat: 30.5299,
    lng: 79.5481,
  },
  {
    id: 'j-s3',
    name: 'Pipalkoti Safety Dome',
    locationId: 'joshimath',
    capacity: 450,
    occupancy: 80,
    waterLevel: 90,
    rations: 85,
    medicalKits: 80,
    lat: 30.4728,
    lng: 79.5031,
  },
];

export const INITIAL_RESPONDERS: FieldResponder[] = [
  {
    id: 'res-1',
    name: 'NDMA Rescue Unit-Alpha',
    type: 'Police',
    status: 'idle',
    location: 'District HQ Command Center',
    progress: 0,
    taskId: null,
  },
  {
    id: 'res-2',
    name: 'SDRF Fire & Hazard Unit-3',
    type: 'Fire',
    status: 'idle',
    location: 'Central Valley Station',
    progress: 0,
    taskId: null,
  },
  {
    id: 'res-3',
    name: 'Red Cross Medical Team Delta',
    type: 'Medical',
    status: 'idle',
    location: 'Regional Hospital Hub',
    progress: 0,
    taskId: null,
  },
  {
    id: 'res-4',
    name: 'SEWA Response Volunteers',
    type: 'NGO',
    status: 'idle',
    location: 'Civic Support Warehouse',
    progress: 0,
    taskId: null,
  },
];

export const INITIAL_WORK_ORDERS: WorkOrder[] = [
  {
    id: 'wo-100',
    title: 'Velachery storm drain clearance',
    description: 'Immediate clearance of stormwater conduits to drain excess runoff from Velachery main junction.',
    source: 'Simulator',
    locationId: 'chennai',
    locationName: 'Velachery Lowland (Lake Road)',
    priority: 'critical',
    status: 'pending',
    assignedResponderId: null,
    progress: 0,
  },
  {
    id: 'wo-101',
    title: 'Slope Retaining Wall reinforcement',
    description: 'Provide immediate support beams to the shifting retaining wall in Puthumala to avoid road blockages.',
    source: 'Simulator',
    locationId: 'wayanad',
    locationName: 'Puthumala Slope Area',
    priority: 'medium',
    status: 'pending',
    assignedResponderId: null,
    progress: 0,
  },
  {
    id: 'wo-102',
    title: 'Drainage blockage clearing',
    description: 'Clear structural drainage channels near Sunil Ward to reduce soil pore-water pressure and slow creep rate.',
    source: 'Simulator',
    locationId: 'joshimath',
    locationName: 'Sunil Ward (Slope Creep)',
    priority: 'critical',
    status: 'pending',
    assignedResponderId: null,
    progress: 0,
  },
];

export const CV_PRESET_IMAGES: CvPresetImage[] = [
  {
    id: 'cv-img-1',
    name: 'Mountain Road Pothole',
    url: '/road_pothole.jpg',
    hazardType: 'Road Surface Degradation / Deep Pothole',
    confidence: 94.2,
    locationTag: 'Mundakkai Access Rd (Wayanad)',
    boundingBoxes: [
      {
        x: 15,
        y: 52,
        w: 62,
        h: 38,
        label: 'Pothole (Severity: High)',
        confidence: 94.2,
      },
    ],
  },
  {
    id: 'cv-img-2',
    name: 'Tension Fissure Creep',
    url: '/road_crack.jpg',
    hazardType: 'Tension Crack / Subsidence Creep',
    confidence: 96.8,
    locationTag: 'Sunil Ward Sector-4 (Joshimath)',
    boundingBoxes: [
      {
        x: 3,
        y: 38,
        w: 92,
        h: 56,
        label: 'Fissure Gap (Subsidence Alert)',
        confidence: 96.8,
      },
    ],
  },
];

export const INITIAL_WEATHER: Record<string, WeatherData> = {
  chennai: {
    precipitation: 28.5,
    temperature: 28.0,
    humidity: 88,
    windSpeed: 32.0,
    imdAlertLevel: 'red',
  },
  wayanad: {
    precipitation: 14.5,
    temperature: 22.0,
    humidity: 92,
    windSpeed: 21.5,
    imdAlertLevel: 'orange',
  },
  joshimath: {
    precipitation: 0.0,
    temperature: 13.8,
    humidity: 58,
    windSpeed: 9.0,
    imdAlertLevel: 'yellow',
  },
};

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  // Chennai
  {
    id: 'ann-c-1',
    time: '08:00 AM',
    source: 'Tamil Nadu SDMA',
    message: 'RED ALERT: Extreme rain warnings issued for Chennai. Command centers deployed for stormwater extraction.',
  },
  {
    id: 'ann-c-2',
    time: '09:30 AM',
    source: 'Greater Chennai Corp',
    message: 'IIT Madras relief shelter camp active and provisioning dry rations. Helplines open at 1913.',
  },
  // Wayanad
  {
    id: 'ann-w-1',
    time: '10:45 AM',
    source: 'Kerala SDMA',
    message: 'Orange Alert issued for Vythiri, Mananthavady, and Sulthan Bathery taluks. Avoid travel near steep slopes.',
  },
  {
    id: 'ann-w-2',
    time: '02:30 PM',
    source: 'Wayanad District Collector',
    message: 'Relocation shelters Alpha and Beta are open. Rations and emergency responders are on standby.',
  },
  // Joshimath
  {
    id: 'ann-j-1',
    time: '09:15 AM',
    source: 'Uttarakhand SDMA',
    message: 'Continuous monitoring of tension cracks in Sunil Ward and Manohar Bagh active. Geologists deployed.',
  },
  {
    id: 'ann-j-2',
    time: '01:50 PM',
    source: 'Chamoli DM Office',
    message: 'Pipalkoti Safety Dome operational. Rescue helplines activated. Dial 1077 for emergency support.',
  },
];
