import { HazardMarker, Shelter, FieldResponder, WorkOrder, CvPresetImage } from './types';

export const INITIAL_HAZARD_MARKERS: HazardMarker[] = [
  // Wayanad Markers
  {
    id: 'w-1',
    name: 'Mundakkai Hamlet',
    locationId: 'wayanad',
    risk: 82,
    status: 'danger',
    details: 'Heavy slope instability. Saturated soil. High risk of immediate debris flow.',
    population: 450,
    x: 35,
    y: 65,
  },
  {
    id: 'w-2',
    name: 'Chooralmala Town',
    locationId: 'wayanad',
    risk: 58,
    status: 'warning',
    details: 'River level rising rapidly. Moderate landslide hazard monitored near old bridge.',
    population: 320,
    x: 45,
    y: 50,
  },
  {
    id: 'w-3',
    name: 'Puthumala Slope Area',
    locationId: 'wayanad',
    risk: 65,
    status: 'warning',
    details: 'Runoff velocity increased. Structural cracks noted in three retaining walls.',
    population: 180,
    x: 60,
    y: 70,
  },
  {
    id: 'w-s1',
    name: 'Meppadi Safe Haven (Shelter Alpha)',
    locationId: 'wayanad',
    risk: 8,
    status: 'safe',
    details: 'Low slope angle, concrete reinforced structural base, medical deployment center.',
    population: 0,
    x: 20,
    y: 35,
  },
  {
    id: 'w-s2',
    name: 'Kalpetta Camp (Shelter Beta)',
    locationId: 'wayanad',
    risk: 4,
    status: 'safe',
    details: 'District administration shelter center, high food/medical kit reserves.',
    population: 0,
    x: 15,
    y: 15,
  },

  // Joshimath Markers
  {
    id: 'j-1',
    name: 'Sunil Ward (Slope Creep)',
    locationId: 'joshimath',
    risk: 86,
    status: 'danger',
    details: 'Wide structural cracks (5cm+) in buildings. Ground subsidence active at 1.2cm/week.',
    population: 290,
    x: 30,
    y: 55,
  },
  {
    id: 'j-2',
    name: 'Manohar Bagh Sector',
    locationId: 'joshimath',
    risk: 72,
    status: 'warning',
    details: 'Foundational shifting in residential zone. Ground water pressure rising.',
    population: 410,
    x: 48,
    y: 62,
  },
  {
    id: 'j-3',
    name: 'Marwari Lower Ward',
    locationId: 'joshimath',
    risk: 45,
    status: 'warning',
    details: 'Seepage from hydro-electric tunnel bypass monitored. Minor rockfall risk.',
    population: 150,
    x: 65,
    y: 45,
  },
  {
    id: 'j-s1',
    name: 'Pipalkoti Safety Dome',
    locationId: 'joshimath',
    risk: 3,
    status: 'safe',
    details: 'Geologically stable bedrock. Integrated prefab tents, permanent concrete structures.',
    population: 0,
    x: 20,
    y: 20,
  },
  {
    id: 'j-s2',
    name: 'Helang Community Hall',
    locationId: 'joshimath',
    risk: 6,
    status: 'safe',
    details: 'Safe elevation, stable foundation. Equipped with communications backup.',
    population: 0,
    x: 75,
    y: 25,
  },
];

export const INITIAL_SHELTERS: Shelter[] = [
  {
    id: 'w-s1',
    name: 'Meppadi Safe Haven (Shelter Alpha)',
    locationId: 'wayanad',
    capacity: 500,
    occupancy: 150, // 30%
    waterLevel: 82,
    rations: 78,
    medicalKits: 85,
  },
  {
    id: 'w-s2',
    name: 'Kalpetta Camp (Shelter Beta)',
    locationId: 'wayanad',
    capacity: 400,
    occupancy: 100, // 25%
    waterLevel: 90,
    rations: 92,
    medicalKits: 80,
  },
  {
    id: 'j-s1',
    name: 'Pipalkoti Safety Dome',
    locationId: 'joshimath',
    capacity: 600,
    occupancy: 180, // 30%
    waterLevel: 95,
    rations: 88,
    medicalKits: 92,
  },
  {
    id: 'j-s2',
    name: 'Helang Community Hall',
    locationId: 'joshimath',
    capacity: 350,
    occupancy: 70, // 20%
    waterLevel: 80,
    rations: 85,
    medicalKits: 75,
  },
];

export const INITIAL_RESPONDERS: FieldResponder[] = [
  {
    id: 'res-1',
    name: 'NDMA Rescue Unit-Alpha',
    type: 'Police',
    status: 'idle',
    location: 'District HQ Command Center',
    progress: 0,
    taskId: null,
  },
  {
    id: 'res-2',
    name: 'SDRF Fire & Hazard Unit-3',
    type: 'Fire',
    status: 'idle',
    location: 'Central Valley Station',
    progress: 0,
    taskId: null,
  },
  {
    id: 'res-3',
    name: 'Red Cross Medical Team Delta',
    type: 'Medical',
    status: 'idle',
    location: 'Regional Hospital Hub',
    progress: 0,
    taskId: null,
  },
  {
    id: 'res-4',
    name: 'SEWA Response Volunteers',
    type: 'NGO',
    status: 'idle',
    location: 'Civic Support Warehouse',
    progress: 0,
    taskId: null,
  },
];

export const INITIAL_WORK_ORDERS: WorkOrder[] = [
  {
    id: 'wo-101',
    title: 'Slope Retaining Wall reinforcement',
    description: 'Provide immediate support beams to the shifting retaining wall in Puthumala to avoid road blockages.',
    source: 'Simulator',
    locationId: 'wayanad',
    locationName: 'Puthumala Slope Area',
    priority: 'medium',
    status: 'pending',
    assignedResponderId: null,
    progress: 0,
  },
  {
    id: 'wo-102',
    title: 'Drainage blockage clearing',
    description: 'Clear structural drainage channels near Sunil Ward to reduce soil pore-water pressure and slow creep rate.',
    source: 'Simulator',
    locationId: 'joshimath',
    locationName: 'Sunil Ward (Slope Creep)',
    priority: 'critical',
    status: 'pending',
    assignedResponderId: null,
    progress: 0,
  },
];

export const CV_PRESET_IMAGES: CvPresetImage[] = [
  {
    id: 'cv-img-1',
    name: 'Mountain Road Pothole',
    url: '/road_pothole.jpg',
    hazardType: 'Road Surface Degradation / Deep Pothole',
    confidence: 94.2,
    locationTag: 'Mundakkai Access Rd (Wayanad)',
    boundingBoxes: [
      {
        x: 15,
        y: 52,
        w: 62,
        h: 38,
        label: 'Pothole (Severity: High)',
        confidence: 94.2,
      },
    ],
  },
  {
    id: 'cv-img-2',
    name: 'Tension Fissure Creep',
    url: '/road_crack.jpg',
    hazardType: 'Tension Crack / Subsidence Creep',
    confidence: 96.8,
    locationTag: 'Sunil Ward Sector-4 (Joshimath)',
    boundingBoxes: [
      {
        x: 3,
        y: 38,
        w: 92,
        h: 56,
        label: 'Fissure Gap (Subsidence Alert)',
        confidence: 96.8,
      },
    ],
  },
];
